### PR TITLE
All scoring rules are implemented

### PR DESCRIPTION
**Pull request by skojaku**
example code
```
block_id = 1
db = scoring.DataBase(conn)
rules = scoring.ScoringRule(db, general_name_list)
rules.eval(block_id)
```

### CODE REVIEW

**Comment by skojaku** [comment]
DataBase class is the interface class between the database and the scoring functions. In the future, the database interface may be re-implemented to directly retrieve data from ElasticSearch or Spark.

**Comment by jisungyoon** [comment]
Overall, looks good.
Have you tired on our entire dataset(COVID-related)?

**Comment by skojaku** [comment]
I haven't tried yet. Just those in testData.csv (where we know the ground truth or the Canadian researchers)

**Comment by XiaoranYan** [comment]
> Overall, looks good.
> Have you tired on our entire dataset(COVID-related)?

 jisung, I forgot to update you that I have replaced the COVID-subset with the full Canadian data by Vincent. You can find details here https://github.com/iuni-cadre/WoS-disambiguation/wiki

**Comment by skojaku** [comment]
1. Implemented all rules and post-process
2. Re-structured the code and split them into the three modules:
   1. DataBlockingAlgorithm.py: Retrieve data from ElasticSearch and create blocks of data based on the authors' initials.
   2. ScoringRule.py: Compute the matching scores
   3. LeidenDisambiguationAlgorithm.py: A class that holds the above two classes. It creates a working directory, save intermediate files (e.g., blocked data, clustered author-paper pairs), and outputs a list of the disambiguated authors 
3. Wrap the code for disambiguation as a package (libs/leiden_algorithm/leiden_algorihtm)

Example: See workflow/disambiguate.py
```python
import numpy as np
import pandas as pd
import os
import sys

sys.path.append(os.path.abspath(os.path.join("libs/leiden_algorithm")))
from leiden_algorithm import LeidenDisambiguationAlgorithm


if __name__ == "__main__":

    ES_USERNAME = sys.argv[1]
    ES_PASSWORD = sys.argv[2]
    ES_ENDPOINT = sys.argv[3]
    INPUT_WOS_FILE = sys.argv[4]
    CITATION_DB = sys.argv[5]
    GENERAL_NAME_LIST_FILE = sys.argv[6]
    WORKING_DIR = sys.argv[7]
    OUTPUT = sys.argv[8]

    wos_ids = pd.read_csv(INPUT_WOS_FILE)["UID"].drop_duplicates().values.tolist()

    general_name_list = pd.read_csv(GENERAL_NAME_LIST_FILE)["first_name"].values

    lda = LeidenDisambiguationAlgorithm(
        WORKING_DIR,
        ES_USERNAME,
        ES_PASSWORD,
        ES_ENDPOINT,
        CITATION_DB,
        general_name_list,
    )

    lda.init_working_dir()
    lda.data_blocking(wos_ids)
    lda.clustering()
    lda.post_process()

    disambiguted_author_list = lda.get_disambiguated_authors()
    disambiguted_author_list.to_csv(OUTPUT, index=False)
```

**Comment by skojaku** [comment]
@XiaoranYan, I have implemented the code and would like to run the algorithm for validation (the results of which will be passed to @jisungyoon for evaluation). I think I should use /gpfs/sciencegenome/WoS-disambiguation/disambiguationBenchmarkLabels.csv as the input but it seems like I don't have read access. Could you directly send me the file or change the permission?

Thanks!

**Comment by XiaoranYan** [comment]
> @XiaoranYan, I have implemented the code and would like to run the algorithm for validation (the results of which will be passed to @jisungyoon for evaluation). I think I should use /gpfs/sciencegenome/WoS-disambiguation/disambiguationBenchmarkLabels.csv as the input but it seems like I don't have read access. Could you directly send me the file or change the permission?
> 
> Thanks!

The permission system is very strange indeed. I am having issue accessing the MAG-2020-09-01 folder on ember myself. You can download the same file at /N/project/rcsc/shared_space/testYan30/ from carbonate. I suggest we create a shared folder on ember/cinder, git clone this repo and save a copy of the file over there, so that all of us can test the algorithm.

**Pull request merged**
